AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - example.micronaut::vat-validator-graal
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: s3://oci-oss-work/69ddbad2afa313cf34e663e36d22a230
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
Outputs:
  MyServiceApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/validate-vat
    Export:
      Name: MyServiceApi
