So unlike the previous guide, this lambda operates just like a standard Micronaut app.

We'll replace the `ExampleController.java` with with a `VatValidationController`, similar to the `ViesVatValidatorFunction`
in the previous guide in logic.

[source,java]
.vat-validator-graal/src/main/java/example.micronaut.VatValidationController.java
----
include::{sourceDir}/vat-validator-graal/src/main/java/example.micronaut.VatValidationController.java
----
<1> Note this is just like a regular Micronaut controller, using the `@Controller` annotation
<2> Be sure to add a `LOG` so that you will be able to see log output in CloudWatch
<3> We want to use constructor-based injection to get our `VatService` in the controller
<4> AWS Lambda doesn't support non-blocking return types so we need to `blockingGet` the service output

We'll also want to modify the `logback.xml` to set the DEBUG level for our `example.micronaut` package.

[source,xml]
.vat-validator-graal/src/main/resources/logback.xml
----
include::{sourceDir}/vat-validator-graal/src/main/resources/logback.xml
----
<1> This is the line that sets the log level to DEBUG